#include <iostream>
using namespace std;

void inputSales(int sArray[7][5]);
void weeklyEachSale(int sArray[7][5]);
void bestDay(int sArray[7][5]);

int main()
{
    system("cls");
    int sales[7][5];
    inputSales(sales);
    cout << endl
         << endl;
    weeklyEachSale(sales);
    cout << endl;
    bestDay(sales);

    return 0;
}

void inputSales(int sArray[7][5])
{
    for (int i = 0; i < 7; i++)
    {
        cout << "\nEnter sales for day: " << i + 1 << endl
             << endl;
        for (int j = 0; j < 5; j++)
        {
            cout << "Sales of product: " << j + 1 << endl;
            cin >> sArray[i][j];
        }
    }
}


void weeklyEachSale(int sArray[7][5])
{
    int p1 = 0, p2 = 0, p3 = 0, p4 = 0, p5 = 0;
    int sales[5] = {0};
    for (int i = 0; i < 7; i++)
    {
        for (int j = 0; j < 1; j++)
        {
            p1 = p1 + sArray[i][j];
            p2 = p2 + sArray[i][j + 1];
            p3 = p3 + sArray[i][j + 2];
            p4 = p4 + sArray[i][j + 3];
            p5 = p5 + sArray[i][j + 4];
        }
    }
    sales[0] = p1;
    sales[1] = p2;
    sales[2] = p3;
    sales[3] = p4;
    sales[4] = p5;

    int maxRevenue = sales[0];
    int maxProduct =1;
    for (int k = 0; k < 5; k++)
    {
        cout << "Sales of Product: " << k + 1 << " is : " << sales[k] << endl;
        if (sales[k] > maxRevenue)
        {
            maxRevenue = sales[k];
            maxProduct = k + 1;
        }
    }
    cout << "Maximum weekly revenue is: " << maxRevenue << " generated by Product: " << maxProduct << endl;
}

void bestDay(int sArray[7][5])
{
    int maxSale = 0;
    int maxDay =1;
    for (int i = 0; i < 7; i++)
    {
        int dailySale = 0;
        for (int j = 0; j < 5; j++)
        {
            dailySale += sArray[i][j];
        }
        if (maxSale < dailySale)
        {
            maxSale = dailySale;
            maxDay = i + 1;
        }
    }

    cout << "The best sale day is: " << maxDay << " and sale is: " << maxSale << endl;
}